require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - 'bin/*'
    - 'tmp/**/*'
    - 'db/schema.rb'

Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 10

RSpec/ExampleLength:
  Max: 10
